### PR TITLE
[DONE] Shows proper asset icons for measuringstations in Omnibox

### PR DESCRIPTION
**Pull request by gijs**
Fixes https://github.com/nens/lizard-nxt/issues/2142

### CODE REVIEW

**Comment by ernstkui** [comment]
Measuringstations have different icons on the map. This is specified in CartoCSS here: https://github.com/nens/nens-carto/blob/master/project/lizardnxt/structures.mss#L308-L329

We should have similar logic in the getIconClass function.

**Comment by gijs** [comment]
Ok, so they have an integer property `station_type` I can add to `getIconClass()`? Will do.

**Comment by gijs** [comment]
Going after this one now

**Comment by gijs** [comment]
Ga jij deze testen & mergen @ernstkui ?

**Comment by ernstkui** [comment]
This fixes it in the front-end:

image

Search results do not include the station_type, so we cannot draw the right icon for every result right now, maybe we can add this next week, the front-end is ready for it!

image

**Pull request merged**
