### PR TITLE
Dutch term now in English

### PR DESCRIPTION
**Pull request by gijs**
Fixes https://github.com/nens/lizard-nxt/issues/2077

### CODE REVIEW

**Comment by ernstkui** [comment]
@gijs the title will not get translated this way. See: https://angular-gettext.rocketeer.be/dev-guide/annotate/

**Comment by ernstkui** [comment]
And the commit should be according to the commit guidelines: https://github.com/nens/lizard-client#commit-message-convention-at-a-glance

**Comment by gijs** [comment]
@ernstkui Done. Did I write the commit message properly?

**Comment by ernstkui** [comment]
Yes awesome

**Pull request merged**
