### PR TITLE
[Done] NPM instead of global grunt and improve dev, build, release, deploy and documentation

### PR DESCRIPTION
**Pull request by ernstkui**
See [README in view](https://github.com/nens/lizard-client/blob/dd927eba0f63d3bea9631543e9ab145f7a51ec40/README.md).

- Gruntfile: remove cdnify task, files are served in one vendor file. Cdns do not add anything to this.
- Gruntfile: jshint everything on test, not just changed files.
- Gruntfile: rename public task transifexUpload to transifex.
- Grunt: Exclude grunt-cli from global requirements.
- Jenkinsfile: call npm scripts.
- Jenkinksfile: use npm install --optional=false to save some node_modules on jenkins server.
- Package.json: wrap all commands with npm to create a consistent api for all nens javascript packages.
- Documentation: remove obsolete stuff and restructure documentation.

Try running: 

```sh
npm run dist
```
And see what happens if you do not have transifex credentials as env variable

Try
```sh
export TRANSIFEX_USERNAME=<username>
export TRANSIFEX_PASSWORD=<password>
npm run dist
```
To see it with env variables.

### CODE REVIEW

**Comment by RoelvandenBerg** [comment]
@gijs volgens mij ben jij degene die hier de beste kijk op heeft. Ik ben hier in iedergeval niet de beste reviewer voor.

**Comment by ernstkui** [comment]
@gijs What d'ya say?

**Comment by gijs** [comment]
I'm going to look at this tomorrow, ok?

**Comment by ernstkui** [comment]
@gijs Today is tomorrow right?

**Comment by gijs** [comment]
Yeah sorry was occupied with other things. It's on my to do list though

**Pull request merged**
