### PR TITLE
[ON HOLD] feat(raster animation): rasters can be animated without flickering

### PR DESCRIPTION
**Pull request by d-weeteling**
I think the best thing we can do is to rewrite the raster animation part, with a single new constraint:
the temporal extent remains fixed when the animation is playing; if the user wants to change the temporal extent, (s)he needs to first pause the animation. Please discuss @JoepGrispen @gijs @remcogerlich @lexvand

### CODE REVIEW

**Comment by d-weeteling** [comment]
An "easy way out" solution is already in this PR: by increasing the buffersize for the animation the problem (= flickering animation) becomes way less obvious. The flickering only occurrs during the last frame of the buffer, and in the old code this buffersize mostly had a size of 2: every second frame the flickering occurred.

By making the buffersize dependent on (i) the temporal extent (=> client state) and (ii) the raster's temporal resolution (=> server config) we can load the required frames (amount capped at a certain maximum) in advance. The price we pay for this easy solution:

1) Client has to wait a little longer after pressing play button, before the animation actually starts the client has too wait (a little) longer.
2) In case more frames than the cap value (e.g. 50) are required given the current temp. extent vs. temporal resolution, the client witnesses a single graphic hiccup after those 50 frames are past.

**Comment by RoelvandenBerg** [comment]
I don't get the problem. Imho, your previous solution: setting a fixed buffer size to the maximal extend, is not a sustainable fix (and it doesn't solve the flickering problem, it partially replaces it with a waiting problem). Why pause the animation? What would your new implementation look like. What does it solve? How do you look at this as a fix? Please elaborate, or even better: I think it would be better if we take some time sit together and think of a solution. @gijs mentioned he might know a library or a method you can use.

**Comment by d-weeteling** [comment]
The preferred implementation has a dynamic buffer for frames, but does not allow for changing the temp. extent while animating. This is because changing the temp. extent may change the aggregation window, which would instantatiously invalidate all frames in the buffer/require new frames in the buffer. This can be fixed by pausing the animation when the suer changes the temp. extent.

**Comment by gijs** [comment]
Isn't the flickering effect caused by some logic fault such as an off-by-one error in computing the number of frames?

In online video players such as Youtube, whenever the buffer is depleted, the last frame remains visible. If it were to show nothing or a black screen in this case, flickering would appear.

Or is this another kind of flickering we're discussing here?

**Comment by gijs** [comment]
Another technique for animating could be drawing using a canvas layer, but this brings its own set of problems, so I would advise against it at this point.

**Comment by JoepGrispen** [comment]
I think we will have to discuss the handling of animation in more detail setting up the new front-end.
I love the way Lizard handles animations especially with Rain but when we look at 3Di secanrio's we encounter a lot of problems. 

The amount of data in one scenario will grow exponentially. Interacting smoothly in a more on the fly experience is nice but maybe too far fetched. @RoelvandenBerg you talk about a waiting problem but in my opinion that is far less a problem than faltering user experience .

to be continued

**Comment by d-weeteling** [comment]
Already fixed in master

**Pull request closed without merging**
