### PR TITLE
[DONE] Adds calc(100%-50) to keep the timeline available at all times

### PR DESCRIPTION
**Pull request by gijs**
Should fix https://github.com/nens/lizard-nxt/issues/2118

### CODE REVIEW

**Comment by gijs** [comment]
@ernstkui Can you verify if this solves the problem on your machine as well?

**Comment by ernstkui** [comment]
I am on it

**Comment by ernstkui** [comment]
image

It does not really fix it. I can click on the lowest 50px but not on the rest. The item timeline can grow. Also the css class omniboxWrapper should be in kebab-case. 

The use of z-index messes stuff up a little. It causes this bug, but also other things which rely on the painter algorithm:

image
User is still able to search when the rest of the app is shutdown.

**Comment by ernstkui** [comment]
We should think of a better solution

**Comment by gijs** [comment]
Maybe the whole wrapper isn't needed anymore? I introduced it because the UX design had this 100% filling vertical omnibox...

**Pull request merged**
