### PR TITLE
Searchbox 'looking glass'

### PR DESCRIPTION
**Pull request by gijs**
- Adds a looking glass when the search input has no focus/value.
- Dims bootstrap placeholder color
- Search background is actually white opaque now (as designed)
- Has Ernst's zoombuttons styling merged in...

screen shot 2016-12-15 at 11 35 05

### CODE REVIEW

**Comment by ernstkui** [comment]
@gijs Ben je er een beetje uitgekomen met de commit guidelines?

**Comment by gijs** [comment]
@ernstkui ja, zie https://github.com/nens/lizard-client/pull/788/commits/edb18107f78afaa538ac133e7f289391b7f08bd1

**Comment by d-weeteling** [comment]
Please make this branch mergable

**Comment by gijs** [comment]
OK ik heb master gemerged @d-weeteling

**Pull request closed without merging**
